# Site Settings
title: Wayne Pooley - Personal Portfolio
email: email@email.com
description: >
  My website
# baseurl: '/startjekyll'
baseurl:
url: 'https://wayne-pooley.github.io'
twitter_username: 
github_username:  wapo6604
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages', '_research']
kramdown:
  input: GFM
