# Site Settings
title: Thomas Zheng - Personal Portfolio
email: email@email.com
description: >
  My website
# baseurl: '/startjekyll'
baseurl:
url: 'https://thomas-hy-zheng.github.io'
twitter_username: 
github_username:  thomas-hy-zheng
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages', '_research']
kramdown:
  input: GFM
