# Site Settings
title: Thomas Zheng - Personal Portfolio
email: email@email.com
description: >
  My website
baseurl: ""
url: "http://localhost:4000"
twitter_username: 
github_username:  thomas-hy-zheng
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM